sudo: required
services:
  - docker

before_install:
  - docker build -t maniizu/react-test -f ./client/Dockerfile.dev ./client #./clientの中からDockerfile.devを探す

script:
  - docker run CI=true maniizu/react-test npm test

after_success:
  - docker build -t maniizu/multi-client ./client
  - docker build -t maniizu/multi-nginx ./nginx
  - docker build -t maniizu/multi-server ./server
  - docker build -t maniizu/multi-worker ./worker
  - docker login -u ${DOCKER_ID} -p ${DOCKER_PASSWORD}
  - docker push maniizu/multi-client
  - docker push maniizu/multi-server
  - docker push maniizu/multi-worker
  - docker push maniizu/multi-nginx
